#ifndef EVEN_FIBONACCI_NUMBERS
#define EVEN_FIBONACCI_NUMBERS

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

int FIRST_NUMBER = 1;
int SECOND_NUMBER = 2;
int CEILING_NUMBER = 4000000;

#endif // EVEN_FIBONACCI_NUMBERS
